name: vfrmap

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: install go-bindata
      run: sudo apt-get install -y go-bindata

    - name: set up go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: checkout repository
      uses: actions/checkout@v2

    - name: get go dependencies
      run: |
        go get -v -t -d ./...
        
    - name: download and generate vfrmap html dependencies
      working-directory: ./vfrmap
      run: make generate

    - name: build
      working-directory: ./vfrmap
      run: GOOS=windows GOARCH=amd64 go build -v -o bin/vfrmap.exe .

    - name: archive vfrmap
      uses: actions/upload-artifact@v2
      with:
        name: vfrmap
        path: ./vfrmap/bin
